# "iso 3166 country": "continent code"
---
AP: AS
EU: EU
AD: EU
AE: AS
AF: AS
AG: SA
AI: SA
AL: EU
AM: AS
AN: SA
AO: AF
AQ: AN
AR: SA
AS: OC
AT: EU
AU: OC
AW: SA
AZ: AS
BA: EU
BB: SA
BD: AS
BE: EU
BF: AF
BG: EU
BH: AS
BI: AF
BJ: AF
BM: SA
BN: AS
BO: SA
BR: SA
BS: SA
BT: AS
BV: AF
BW: AF
BY: EU
BZ: SA
CA: NA
CC: AS
CD: AF
CF: AF
CG: AF
CH: EU
CI: AF
CK: OC
CL: SA
CM: AF
CN: AS
CO: SA
CR: SA
CU: SA
CV: AF
CX: AS
CY: AS
CZ: EU
DE: EU
DJ: AF
DK: EU
DM: SA
DO: SA
DZ: AF
EC: SA
EE: EU
EG: AF
EH: AF
ER: AF
ES: EU
ET: AF
FI: EU
FJ: OC
FK: SA
FM: OC
FO: EU
FR: EU
FX: EU
GA: AF
GB: EU
GD: SA
GE: AS
GF: SA
GH: AF
GI: EU
GL: SA
GM: AF
GN: AF
GP: SA
GQ: AF
GR: EU
GS: SA
GT: SA
GU: OC
GW: AF
GY: SA
HK: AS
HM: AF
HN: SA
HR: EU
HT: SA
HU: EU
ID: AS
IE: EU
IL: AS
IN: AS
IO: AS
IQ: AS
IR: AS
IS: EU
IT: EU
JM: SA
JO: AS
JP: AS
KE: AF
KG: AS
KH: AS
KI: OC
KM: AF
KN: SA
KP: AS
KR: AS
KW: AS
KY: SA
KZ: AS
LA: AS
LB: AS
LC: SA
LI: EU
LK: AS
LR: AF
LS: AF
LT: EU
LU: EU
LV: EU
LY: AF
MA: AF
MC: EU
MD: EU
MG: AF
MH: OC
MK: EU
ML: AF
MM: AS
MN: AS
MO: AS
MP: OC
MQ: SA
MR: AF
MS: SA
MT: EU
MU: AF
MV: AS
MW: AF
MX: NA
MY: AS
MZ: AF
NA: AF
NC: OC
NE: AF
NF: OC
NG: AF
NI: SA
NL: EU
NO: EU
NP: AS
NR: OC
NU: OC
NZ: OC
OM: AS
PA: SA
PE: SA
PF: OC
PG: OC
PH: AS
PK: AS
PL: EU
PM: SA
PN: OC
PR: SA
PS: AS
PT: EU
PW: OC
PY: SA
QA: AS
RE: AF
RO: EU
RU: AS
RW: AF
SA: AS
SB: OC
SC: AF
SD: AF
SE: EU
SG: AS
SH: AF
SI: EU
SJ: EU
SK: EU
SL: AF
SM: EU
SN: AF
SO: AF
SR: SA
ST: AF
SV: SA
SY: AS
SZ: AF
TC: SA
TD: AF
TF: AF
TG: AF
TH: AS
TJ: AS
TK: OC
TM: AS
TN: AF
TO: OC
TP: AS
TR: AS
TT: SA
TV: OC
TW: AS
TZ: AF
UA: EU
UG: AF
UM: OC
US: NA
UY: SA
UZ: AS
VA: EU
VC: SA
VE: SA
VG: SA
VI: SA
VN: AS
VU: OC
WF: OC
WS: OC
YE: AS
YT: AF
YU: EU
ZA: AF
ZM: AF
ZR: AF
ZW: AF
